modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "embeddiumextension"
version = "${version}"
displayName = "EmbeddiumExtension"
authors="TeamPotato"
description = '''

'''