modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "embeddiumextension"
version = "${version}"
displayName = "EmbeddiumExtension"
authors="TeamPotato"
description = '''

'''

[[dependencies.embeddiumextension]]
modId="embeddium"
mandatory=true
versionRange="[0.1.14+mc1.16.5,)"
ordering="NONE"
side="BOTH"